server:
    port: 8090
    servlet:
      contextPath: /api

spring:
  application:
    name: oauth-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
