server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  application:
    name: oauth-authorization-server
  security:
    user:
      name: test
      password: password
    oauth2:
      authorizationserver:
        client:
          oauth-client:
            registration:
              client-id: "oauth-client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/articles-client-authorization-code"
                - "http://localhost:8080/login/oauth2/code/articles-client-authorization-code"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080"
                - "http://localhost:8080"
              scopes:
                - "openid"
                - "products:read"
          public-oauth-client:
            registration:
              client-id: "public-oauth-client"
              client-authentication-methods:
                - "none"
              authorization-grant-types:
                - "authorization_code"
              redirect-uris:
                - "http://127.0.0.1:8081"
                - "http://localhost:8081"
                - "http://127.0.0.1:4200"
                - "http://localhost:4200"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8081"
                - "http://localhost:8081"
                - "http://127.0.0.1:4200"
                - "http://localhost:4200"
              scopes:
                - "openid"
                - "products:read"
            require-proof-key: true
