server:
    port: 8443
    ssl:
        key-store: classpath:keystore/localhost.p12
        key-store-type: PKCS12
        key-store-password: isnich
        key-alias: localhost
        enabled: true


spring:
    application:
        name: ldap-client
